stages:
  - deploy

Deploying Web Staging:
  stage: deploy
  script:
    - echo "Deploying Web Staging..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_staging_web_deploy
    - echo "Web Staging deployed successfully"
  only:
    - staging
  environment: Staging

Deploying Web Production:
  stage: deploy
  script:
    - echo "Deploying US Web Production..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_production_web_deploy
    - echo "US Web Production deployed successfully"
    - echo "Deploying CAN Web Production..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py can_production_web_deploy
    - echo "CAN Web Production deployed successfully"
  only:
    - master
  environment: Production