stages:
  - test
  - build
  - deploy

## Staging
Testing Web Staging:
  stage: test
  script:
    - echo "Testing Web Staging..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_staging_web_test
    - echo "Web Staging tested successfully"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
      changes:
        - 'projects/campus-cloud/**/*'
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - campus-cloud/
  environment: Staging

Building Web Staging:
  stage: build
  script:
    - echo "Building Web Staging..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_staging_web_build
    - echo "Web Staging built successfully"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
      changes:
        - 'projects/campus-cloud/**/*'
  environment: Staging

Deploying Web Staging:
  stage: deploy
  script:
    - echo "Deploying Web Staging..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_staging_web_deploy
    - echo "Web Staging deployed successfully"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
      changes:
        - 'projects/campus-cloud/**/*'
  environment: Staging

## US Production

Building Web Production:
  stage: build
  script:
    - echo "Building CC Prod..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py production_web_build
    - echo "CC Prod built successfully"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      changes:
        - 'projects/campus-cloud/**/*'
  environment: Production

Deploying Web Production:
  stage: deploy
  script:
    - echo "Deploying US Web Production..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py us_production_web_deploy
    - echo "US Web Production deployed successfully"
    - echo "Deploying CAN Web Production..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py can_production_web_deploy
    - echo "CAN Web Production deployed successfully"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      changes:
        - 'projects/campus-cloud/**/*'
  environment: Production

## Ready UI

Deploy Ready UI:
  stage: deploy
  script:
    - echo "Building Ready UI..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py ready_ui_deploy
    - echo "Ready UI successfully deployed"

  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"'
      changes:
        - 'projects/ready-ui/**/*'

## Playground

Deploy Playground:
  stage: deploy
  script:
    - echo "Building Playground..."
    - /ops_data/gitlab-runner/oohlala_env/bin/fab -f /ops_data/gitlab-runner/oohlala-ci/scripts/oohlala_cd.py ready_playground_deploy
    - echo "Playground successfully deployed"

  only:
    refs:
      - staging
    changes:
      - 'projects/playground/**/*'

## Development

Testing Web Development:
  stage: test
  script:
    - echo "Testing Web Dev...$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "TODO - add testing pipeline"
  only:
    - merge_requests
  environment: Development
