phraseapp:
  access_token: fc3e70017b29ed6c6d4bd1c1d3c434ce4eb27c92f3c5206f660cbd56202b9a06
  project_id: d948cd691ed0911393456d90729647d1
  push:
    sources:
      - file: ./projects/campus-cloud/src/app/config/locales/en-US.json
        params:
          file_format: json
          locale_id: 2e536a7f1c09753241b8bc8d0fca3923
      - file: ./projects/campus-cloud/src/app/config/locales/fr-CA.json
        params:
          file_format: json
          locale_id: 2a321e373ca3e611f32dff0f1efb2ac2
  pull:
    targets:
      - file: ./projects/campus-cloud/src/app/config/locales/en-US.json
        params:
          file_format: json
          locale_id: 2e536a7f1c09753241b8bc8d0fca3923
      - file: ./projects/campus-cloud/src/app/config/locales/fr-CA.json
        params:
          file_format: json
          include_empty_translations: true
          locale_id: 2a321e373ca3e611f32dff0f1efb2ac2
          fallback_locale_id: 2e536a7f1c09753241b8bc8d0fca3923
