/*tslint:disable:max-line-length */
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { OverlayModule } from '@angular/cdk/overlay';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';

// directives
import {
  CPHostDirective,
  CPTargetDirective,
  CPTrackerDirective,
  CPToolTipDirective,
  CPLightboxDirective,
  CPImageRatioDirective,
  CPColorPickerDirective,
  CPFeatureToggleDirective
} from './directives';

// services
import {
  StoreService,
  CPMapsService,
  CPTrackingService,
  FileUploadService,
  CPLocationsService,
  CPAmplitudeService
} from './services';

import { LocationsService } from '../containers/controlpanel/manage/locations/locations.service';
import { CPLineChartUtilsService } from './components/cp-line-chart/cp-line-chart.utils.service';
import { CPRangePickerUtilsService } from './components/cp-range-picker/cp-range-picker.utils.service';

// pipes
import { CPDatePipe, CPFilterPipe, CPI18nPipe, CPFIlterByLength } from './pipes';

// components
import { CPTabsComponent } from './components/cp-tabs/components/cp-tabs/cp-tabs.component';

import { LatLngValidators } from '@campus-cloud/shared/validators';

import {
  CPTabComponent,
  CPCardComponent,
  CPChipComponent,
  CPMapsComponent,
  CPMenuComponent,
  CPAlertComponent,
  CPModalComponent,
  CPStarsComponent,
  CPImageComponent,
  CPAvatarComponent,
  CPButtonComponent,
  CPTopBarComponent,
  CPSwitchComponent,
  CPWorkingComponent,
  CPSpinnerComponent,
  CPMenuItemComponent,
  CPSnackBarComponent,
  CPCheckboxComponent,
  CPDropdownComponent,
  CPLightboxComponent,
  CPTrackersComponent,
  CPTopBanerComponent,
  CPFormLabelComponent,
  CPTypeAheadComponent,
  CPSearchBoxComponent,
  CPLineChartComponent,
  CPListModalComponent,
  CPNoContentComponent,
  CPDatePickerComponent,
  CPHeaderLinkComponent,
  CPPageHeaderComponent,
  CPPaginationComponent,
  CPTextEditorComponent,
  SchoolSwitchComponent,
  CPDeleteModalComponent,
  CPRangePickerComponent,
  CPImageUploadComponent,
  CPUploadModalComponent,
  CPCharCounterComponent,
  CPUploadButtonComponent,
  CPImageCropperComponent,
  CPCheckDropdownComponent,
  CPSortingHeaderComponent,
  CPResourceBannerComponent,
  CPSmallDatePickerComponent,
  CPFormFixedFooterComponent,
  CPUploadModalBodyComponent,
  CPPlaceAutoCompleteComponent,
  CPUploadModalFooterComponent,
  CPUploadModalHeaderComponent,
  CPDropdownMultiSelectComponent
} from './components';

@NgModule({
  declarations: [
    CPI18nPipe,
    CPDatePipe,
    CPFilterPipe,
    CPTabComponent,
    CPCardComponent,
    CPHostDirective,
    CPMapsComponent,
    CPMenuComponent,
    CPTabsComponent,
    CPChipComponent,
    CPImageComponent,
    CPStarsComponent,
    CPModalComponent,
    CPAlertComponent,
    CPFIlterByLength,
    CPSwitchComponent,
    CPTopBarComponent,
    CPAvatarComponent,
    CPTargetDirective,
    CPButtonComponent,
    CPSpinnerComponent,
    CPToolTipDirective,
    CPTrackerDirective,
    CPWorkingComponent,
    CPMenuItemComponent,
    CPTopBanerComponent,
    CPDropdownComponent,
    CPCheckboxComponent,
    CPTrackersComponent,
    CPSnackBarComponent,
    CPLightboxDirective,
    CPFormLabelComponent,
    CPLightboxComponent,
    CPNoContentComponent,
    CPTypeAheadComponent,
    CPSearchBoxComponent,
    CPListModalComponent,
    CPLineChartComponent,
    CPPageHeaderComponent,
    CPDatePickerComponent,
    CPImageRatioDirective,
    CPPaginationComponent,
    CPTextEditorComponent,
    CPHeaderLinkComponent,
    SchoolSwitchComponent,
    CPUploadModalComponent,
    CPColorPickerDirective,
    CPDeleteModalComponent,
    CPImageUploadComponent,
    CPRangePickerComponent,
    CPCharCounterComponent,
    CPImageCropperComponent,
    CPUploadButtonComponent,
    CPSortingHeaderComponent,
    CPCheckDropdownComponent,
    CPFeatureToggleDirective,
    CPResourceBannerComponent,
    CPFormFixedFooterComponent,
    CPSmallDatePickerComponent,
    CPUploadModalBodyComponent,
    CPUploadModalFooterComponent,
    CPUploadModalHeaderComponent,
    CPPlaceAutoCompleteComponent,
    CPDropdownMultiSelectComponent
  ],

  entryComponents: [CPLightboxComponent, CPImageCropperComponent],

  imports: [FormsModule, CommonModule, RouterModule, OverlayModule, ReactiveFormsModule],

  providers: [
    StoreService,
    CPMapsService,
    LocationsService,
    LatLngValidators,
    CPTrackingService,
    FileUploadService,
    CPLocationsService,
    CPAmplitudeService,
    CPLineChartUtilsService,
    CPRangePickerUtilsService
  ],

  exports: [
    CPDatePipe,
    CPI18nPipe,
    CPFilterPipe,
    CPTabComponent,
    CPCardComponent,
    CPMapsComponent,
    CPMenuComponent,
    CPHostDirective,
    CPTabsComponent,
    CPChipComponent,
    CPImageComponent,
    CPFIlterByLength,
    CPStarsComponent,
    CPAlertComponent,
    CPModalComponent,
    CPSwitchComponent,
    CPTopBarComponent,
    CPAvatarComponent,
    CPTargetDirective,
    CPButtonComponent,
    CPTrackerDirective,
    CPSpinnerComponent,
    CPToolTipDirective,
    CPWorkingComponent,
    CPDropdownComponent,
    CPMenuItemComponent,
    CPTrackersComponent,
    CPCheckboxComponent,
    CPSnackBarComponent,
    CPTopBanerComponent,
    CPLightboxComponent,
    CPLightboxDirective,
    CPFormLabelComponent,
    CPListModalComponent,
    CPNoContentComponent,
    CPTypeAheadComponent,
    CPSearchBoxComponent,
    CPLineChartComponent,
    CPHeaderLinkComponent,
    CPTextEditorComponent,
    CPPageHeaderComponent,
    CPDatePickerComponent,
    CPPaginationComponent,
    CPImageRatioDirective,
    SchoolSwitchComponent,
    CPDeleteModalComponent,
    CPImageUploadComponent,
    CPUploadModalComponent,
    CPCharCounterComponent,
    CPColorPickerDirective,
    CPRangePickerComponent,
    CPUploadButtonComponent,
    CPImageCropperComponent,
    CPCheckDropdownComponent,
    CPSortingHeaderComponent,
    CPFeatureToggleDirective,
    CPResourceBannerComponent,
    CPFormFixedFooterComponent,
    CPSmallDatePickerComponent,
    CPUploadModalBodyComponent,
    CPPlaceAutoCompleteComponent,
    CPUploadModalHeaderComponent,
    CPUploadModalFooterComponent,
    CPDropdownMultiSelectComponent
  ]
})
export class SharedModule {}
