export const WALLS_INTEGRATION = 'WALLS_INTEGRATION';
export const ITEMS_INTEGRATION = 'ITEMS_INTEGRATION';
export const EVENTS_INTEGRATION = 'EVENTS_INTEGRATION';
export const ANNOUNCEMENT_INTEGRATION = 'ANNOUNCEMENT_INTEGRATION';
