import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import { CPTrackerDirective } from './directives';
import { CPDatePipe, CPFilterPipe, CPI18nPipe } from './pipes';
import { FileUploadService, StoreService } from './services';
import { CPTrackingService } from './services/tracking.service';

import {
  CPAvatarComponent,
  CPMapsComponent,
  CPModalComponent,
  CPTopBarComponent,
  CPSpinnerComponent,
  CPDropdownComponent,
  CPCheckboxComponent,
  CPPlaceAutoCompleteComponent,
  CPPageHeaderComponent,
  CPSearchBoxComponent,
  CPStarsComponent,
  CPAlertComponent,
  CPDatePickerComponent,
  CPSwitchComponent,
  CPSmallDatePickerComponent,
  CPUploadButtonComponent,
  CPPaginationComponent,
  CPNoContentComponent,
  CPCheckDropdownComponent,
  CPImageUploadComponent,
  SchoolSwitchComponent,
  CPTrackersComponent,
  CPChipComponent,
  CPTypeAheadComponent,
  CPUploadModalComponent,
  CPSnackBarComponent,
  CPButtonComponent,
  CPTextEditorComponent,
  CPTopBanerComponent,
  CPTooltipComponent,
} from './components';

@NgModule({
  declarations: [
    CPTopBarComponent,
    CPMapsComponent,
    CPAvatarComponent,
    CPModalComponent,
    CPPlaceAutoCompleteComponent,
    CPUploadButtonComponent,
    CPSpinnerComponent,
    CPDropdownComponent,
    CPCheckboxComponent,
    CPPageHeaderComponent,
    CPSearchBoxComponent,
    CPDatePipe,
    CPStarsComponent,
    CPFilterPipe,
    CPAlertComponent,
    CPAlertComponent,
    CPDatePickerComponent,
    CPSwitchComponent,
    CPDatePickerComponent,
    CPSmallDatePickerComponent,
    CPPaginationComponent,
    CPNoContentComponent,
    CPCheckDropdownComponent,
    CPImageUploadComponent,
    SchoolSwitchComponent,
    CPTrackersComponent,
    CPUploadModalComponent,
    CPChipComponent,
    CPTypeAheadComponent,
    CPSnackBarComponent,
    CPTrackerDirective,
    CPButtonComponent,
    CPTextEditorComponent,
    CPI18nPipe,
    CPTopBanerComponent,
    CPTooltipComponent,
  ],

  imports: [CommonModule, RouterModule, ReactiveFormsModule],

  providers: [StoreService, FileUploadService, CPTrackingService],

  exports: [
    CPTopBarComponent,
    CPMapsComponent,
    CPAvatarComponent,
    CPModalComponent,
    CPPlaceAutoCompleteComponent,
    CPUploadButtonComponent,
    CPSpinnerComponent,
    CPDropdownComponent,
    CPCheckboxComponent,
    CPPageHeaderComponent,
    CPSearchBoxComponent,
    CPDatePipe,
    CPStarsComponent,
    CPFilterPipe,
    CPAlertComponent,
    CPAlertComponent,
    CPDatePickerComponent,
    CPSwitchComponent,
    CPDatePickerComponent,
    CPSmallDatePickerComponent,
    CPPaginationComponent,
    CPNoContentComponent,
    CPCheckDropdownComponent,
    CPImageUploadComponent,
    SchoolSwitchComponent,
    CPTrackersComponent,
    CPUploadModalComponent,
    CPChipComponent,
    CPTypeAheadComponent,
    CPSnackBarComponent,
    CPTrackerDirective,
    CPButtonComponent,
    CPTextEditorComponent,
    CPI18nPipe,
    CPTopBanerComponent,
    CPTooltipComponent,
  ],
})
export class SharedModule {}
